apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-frService
spec:
  selector:
    matchLabels:
      app: sdci-frService
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-frService
    spec:
      containers:
      - name: sdci-frService-container
        image: queenie2002/sdci-project:gf
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REMOTE_IP_GI
          value: "sdci-gi-clusterip"
